---
title: The SSPHub, the network for data scientists
---

# The SSPHub, the network for data scientists

The network of [Official Statistical System (SSP)](https://www.insee.fr/en/information/2386424) data scientists is made up mainly, but not exclusively, of **the government departments responsible for producing official statistics** (mainly INSEE and ministerial statistical departments).

The network has several objectives, the main ones being:

- The **sharing and disseminating knowledge** within the *data scientists* community around the practices and innovations of the *data-science* ;
- The **innovative work** in the field of statistical production ;
- Facilitate **exchanges between peers** The aim is to facilitate exchanges between peers, whether or not they belong to the official statistical service.

In order to better define the objectives, target audience, themes addressed by the network, and associated resources, a [manifesto ](/additional/manifeste.html) was drafted collectively.

# Would you like to join the network?

The network is open to anyone working in the production of official statistics and more widely in the civil service. There are various ways in which you can join:

- You can join our discussion channel \[`Tchap`\]({{\< var contact.tchap >}}) ;
- You can receive the newsletter by registering [here] ({{\< var signup.form >}}) ;
- You can take part in the creation of content on this site at [our `Github` {{\< fa brands github >}}](https://github.com/InseeFrLab/ssphub) ;
- If you have any questions, would like to chat, etc., you can also send an e-mail to {{\< var contact.email >}}.

# The SSP Lab, INSEE's data science innovation laboratory, which also runs the SSPHub.

The SSPLab also manages the SSPHub network.
The SSPLab is an INSEE unit (equivalent to a division or office) which was created following the Insee-2025 medium-term strategy reflections. [^1] .
Part of the Methodology, Statistical and International Coordination Directorate (the famous DMCSI), the SSP Lab **promotes innovation and novelty in data sources, technologies and data science methods**.
To this end, it conducts experimental projects in support of the sponsoring departments responsible for producing official statistics (including SSMs outside INSEE, INSEE's business divisions and regional directorates).
It also provides **monitoring role** and **dissemination of innovative statistical methods** co-organises the SSPHub and acts as a link between **external partners** in areas within its remit (research laboratories, European peers).

[^1]: More details are available on the Insee website[here (French)](https://www.insee.fr/fr/information/3559883)


