---
toc: false
sidebar: false
title-block-style: none
css: assets/css/homepage.css
page-layout: full
listing:
  - id: project
    contents: project/**/index.qmd
    type: grid
    feed: true
    sort:
      - "date desc"
  # - id: blog_event
  #   contents: 
  #   - blog
  #   - event
  #   type: grid
  #   feed: true
  #   sort:
  #     - "date desc"
  #   page-size: 9
  # - id: newsletters
  #   contents: infolettre/infolettre_*/index.qmd
  #   type: grid
  #   sort:
  #     - "number desc"
  #   feed: true
  #   page-size: 9
  # - id: partenaires
  #   contents: partenaires
  #   template: scripts/courses.ejs
  #   type: grid
  #   feed: false
echo: false
---



::: {.content-visible when-profile="fr"}

# Le réseau des data scientists de la statistique publique

Le `SSPHub` centralise et vise à faire connaître le contenu créé par
le réseau des _data scientists_ du [Service Statistique Publique (SSP)](https://www.insee.fr/fr/information/1302192).

Une présentation du réseau est 
disponible sur la page [à propos](about.html). 
Pour en savoir plus sur les objectifs du réseau, sa philosophie,
et ses modes d'actions, vous pouvez découvrir le Manifeste 📜.
écrit collectivement. 

:::

::: {.content-visible when-profile="en"}

# Data scientist of the Official Statistical Office

Some english content
:::






::: {.column-page}

::: {.content-visible when-profile="fr"}

## Les derniers billets de blog et événements

L'ensemble des billets de blog peut être retrouvé sur la page dédiée, tout comme les événements.





## Les projets innovants du SSPHub

L'ensemble des projets innovants peut être retrouvé sur la [page dédiée](project.qmd).


:::: {#project}
::::




## Les dernières _newsletters_

Toutes les _newsletters_ précédemment publiées sont disponibles sur la page dédiée.




## Les réseaux partenaires

Quelques communautés de la data-science avec lesquels nous collaborons

:::



::: {.content-visible when-profile="en"}


# With some projects
L'ensemble des projets innovants. 


:::: {#project}
::::

:::

:::


