# Architecture of the project

## Quarto data 
_publish.yml
_quarto-en.yml
_quarto-fr.yml
_quarto.yml
_variables.yml

## French, default, version
Files and folders are presented following the visual website logic: 

- index.qmd

- event.qmd
  - event/
  - other_events.yml : other events to include in the event.qmd listing, without having to create a dedicated folder
- blog.qmd
  - blog/
  - list of blog post whose format is : a dedicated folder and an index.qmd file
- project.qmd
  - project/
  - list of project whose format is : a dedicated folder and an index.qmd file. The project index.qmd file is formatted.
- course.qmd
  - course/
  - list of useful courses / documentation. A course is a dedicated directory, with an image and an index file rerouting to external website
- partenaires/
  - list of partners with a logo and a redirection to their website
Other :
- infolettre/
  - infolettre.qmd
  - list of infolettre : a dedicated folder and an index.qmd file
- manifeste.qmd
- about.qmd

Unused ?
./additional:
notebooks
  polars-tuto.qmd


## English version
about.en.qmd
index.en.qmd
project.en.qmd

## Assets

### CSS and other
./assets:
css
media
scss
webfonts

./_extensions:
coatless
emilhvitfeldt
quarto-ext

### Scripts
./scripts:
courses.ejs
preview.R
render.R
translate.R

### Repo description
CONTRIBUTING.md
init.sh
LICENSE.md
README.md
wiki.qmd
